# Generated by Django 5.1.1 on 2024-10-09 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0004_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourguide.location')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourguide.tour')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='locations',
            field=models.ManyToManyField(through='tourguide.TourLocation', to='tourguide.location'),
        ),
    ]
