# Generated by Django 5.1.1 on 2024-10-10 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0005_tourlocation_tour_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='length',
        ),
    ]
