# Generated by Django 5.1.2 on 2024-10-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0006_remove_tour_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
